import { IpInfos } from '@/types/IpInfos';

export const EMPTY_IP_INFOS: IpInfos = {
  ip: '',
  city: '',
  region: '',
  country: '',
  postal: 0,
  timezone: {
    abbr: '',
    current_time: '',
    is_dst: false,
    id: '',
    offset: 0,
    utc: '',
  },
  latitude: 0,
  longitude: 0,
  success: false,
  type: '',
  continent: '',
  continent_code: '',
  country_code: '',
  region_code: '',
  is_eu: false,
  calling_code: 0,
  capital: '',
  borders: '',
  flag: {
    img: '',
    emoji: '',
    emoji_unicode: '',
  },
  connection: {
    asn: 0,
    org: '',
    isp: '',
    domain: '',
  },
  currency: {
    name: '',
    code: '',
    symbol: '',
    plural: '',
    exchange_rate: 0,
  },
  security: {
    anonymous: false,
    proxy: false,
    vpn: false,
    tor: false,
    hosting: false,
  },
};
