name: Danger CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-danger:
    name: Run Danger
    runs-on: ubuntu-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.DANGER_BOT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: yarn install
      - run: yarn danger ci --dangerfile danger/dangerfile.ts
